### ISSUE TITLE
CPU-spike occurring when `-c` command try to terminate.

### ISSUE THREAD

**Issue by czaplicki** [OmarCastro/cmd-polkit#6] opened 2024-01-24 19:40 UTC
As the title ses, if the command specified with `-c` tries terminate, cmd-polkit-agent will spike in cpu usage.

Somewhat related to: https://github.com/OmarCastro/cmd-polkit/issues/4

Ultimately EOF would be sent to the `-c` command once the interaction is done in order to a signal just that. And then once the command has terminated, the process would be released (to solve https://github.com/OmarCastro/cmd-polkit/issues/4).

**Comment by OmarCastro** [comment] 2024-03-10 01:52
I could not reproduce it, but I hypothesize that it happens due to #4 because of the accumulation of zombie child processes. Now that the issue is solved, I guess this is automatically going to solve

I will close this issue as solved, feel free to open it if the problem still happens

**Closed as completed by OmarCastro** 2024-03-10 01:52 UTC
